blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blogapp.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('single_page/<int:id>', views.SinglePageView.as_view(), name='single_page'),
    path('article_author/<name>', views.AuthorView.as_view(), name='article_author'),
    path('category/<name>', views.CategoryView.as_view(), name='category'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('create_new_category/', views.CreateNewCategoryView.as_view(), name='create_new_category'),
    path('update_category/<int:id>', views.UpdateCategory.as_view(), name='update_category'),
    path('delete_category/<int:id>', views.DeleteCategory.as_view(), name='delete_category'),
    path('create_new_article/', views.CreateNewArticleView.as_view(), name='create_new_article'),
    path('article_update/<int:id>', views.UpdateArticle.as_view(), name='article_update'),
    path('delete_article/<int:id>', views.DeleteArticle.as_view(), name='delete_article'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.RegisterView.as_view(), name='registration'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('pdf/<int:id>', views.render_pdf_view, name='pdf'),

]

blog/templates/author.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <!--article author-->
    <section class="article-author mb-2">
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <button class="btn btn-outline-danger article-author-btn" data-toggle="modal" data-target="#myModal">Author</button>
                </div>
            </div>
            <div class="modal" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title"><strong>Author</strong></h5>
                            <button class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body text-center">
                            <img src="{{auth.image.url}}" class="author-image" alt="" srcset="">
                            <h3 class="mt-2 text-muted">About me</h3>
                            <h4>{{auth.name.get_full_name}}</h4>
                            <h5>{{auth.name.email}}</h5>
                            <p>{{auth.details}}.</p>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-warning" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </section>

    <!--article-->
    <section>
        <div class="container">
            <div class="row mb-4">
                {% for a in articles %}
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card mb-4" style="box-shadow:1px 1px 0px 0px gray">
                        <a href="{{a.single_page_url}}"><img src="{{a.image.url}}" class="card-img-top" alt="" srcset=""></a>
                        <div class="card-body">
                            <b><a href="{{a.category_page_url}}">{{a.category.name}}</a></b>
                            <a href="{{a.single_page_url}}"><strong>{{a.title}}.</strong></a>
                            <b class="text-muted">{{a.article_author.name.get_full_name}}</b>
                        </div>
                        <div class="card-footer">
                            <b><span>{{a.posted_on}}</span></b>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>            
        </div>
    </section>
    {% endblock %}

    {% block pagination %}
    <!-- pagination -->
     <section>
        <div class="container">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        {% if articles.has_previous %}
                        <a class="page-link" href="?page={{ articles.previous_page_number }}">Prev</a>
                        {% endif %}
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a>
                    </li>
                    <li class="page-item">
                        {% if articles.has_next %}
                        <a class="page-link" href="?page={{ articles.next_page_number }}">Next</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        </div>
    </section>
    {% endblock %}

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Best Tech Blogs, Please Share Your Tech Knowledge.</title>
    <link rel="shortcut icon" href="{% static 'images//pic_1.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'fontawesome/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <!--start nav-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
        <div class="container">
            <a href="{% url 'blog:index' %}" class="navbar-brand" id="tech" title="Home page">Tech</a>
            <button class="navbar-toggler" id="btn" data-target="#myNav" data-toggle="collapse"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="myNav">
                <ul class="navbar-nav mx-auto" id="nav">
                    <li class="nav-item">
                        <a href="{% url 'blog:registration' %}" class="nav-link" id="reg">Registration</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'blog:category' %}" class="nav-link" id="cat">Category</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'blog:profile' %}" class="nav-link" id="pro">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'blog:create_new_article' %}" class="nav-link" id="create" style="color:#ffffff; padding: 20px 18px; font-size:15px">Create article</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'blog:logout' %}" class="nav-link" id="logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'blog:login' %}" class="nav-link" id="login">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="ml-3" method="GET">
                    <input type="text" class="form-control" placeholder="Search..." name="q" value="{{request.GET.q}}">
                </form>
            </div>            
        </div>
    </nav>
    {% block bgImage %}
    {% endblock %}
    {% block scrolling %}
    {% endblock %}
    {% block heading %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block show_comment %}
    {% endblock %}
    {% block comment %}
    {% endblock %}
    {% block pagination %}
    {% endblock %}
    <!-- start footer  -->   
    <section>                   
        <footer class="footer-bg">
            <div class="container" id="footer-container">                
                <small style="color: whitesmoke;">Try to your best</small>                              
                <hr>
                <div class="row">                    
                    <div class="col-lg-8 mt-3 mb-3">                        
                        <h3>SUBSCRIBE OUR NEWSLETTER</h3>                        
                    </div>                    
                    <div class="col-lg-4 mt-3 mb-3">
                        <div class="subscribe-form">                                                        
                            <form action="" method="POST">
                                <input type="email" name="" id="" placeholder="Enter your email">
                                <button type="submit">Subscribe</button>              
                            </form>
                        </div>
                    </div>
                </div>                     
                <hr>                
                <div class="row social_link">
                    <div class="col-lg-6 mb-3 text-center">
                        <i class="fab fa-facebook-square"></i>
                        <i class="fab fa-twitter-square"></i>
                        <i class="fab fa-linkedin"></i>
                        <i class="far fa-envelope"></i>
                    </div>
                    <div class="col-lg-6 mb-3 text-center">
                        <i class="fas fa-thumbs-up"></i>
                        <b class="b">Developed by Hachib khan</b>
                        <h6 style="color: white;">&copy; Hachib khan 2020.</h6>
                    </div>
                </div>       
            </div>           
        </footer>    
    </section>
    
    <script src="{% static 'js/jquery-slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nav.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
</body>
</html>

blog/templates/category.html
{% extends 'base.html' %}
{% load static %}

    {% block heading %}
    <!--heading-->
    <div class="heading mt-5 pt-5">
        <p>Similar Type Category {{cat.name}}</p>
    </div>
    {% endblock %}


    {% block content %}
    <!--main content-->
    <section>
        <div class="container">
            <div class="row mb-4">
                {% for a in articles %}
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card mb-4" style="box-shadow:1px 1px 0px 0px gray">
                        <a href="{{a.single_page_url}}"><img src="{{a.image.url}}" class="card-img-top" alt="" srcset=""></a>
                        <div class="card-body">
                            <b class="text-muted">{{a.category.name}}</b>
                            <a href="{{a.single_page_url}}"><strong>{{a.title}}.</strong></a>
                            <b><a href="{{a.article_author_url}}">{{a.article_author.name.get_full_name}}</a></b>
                        </div>
                        <div class="card-footer">
                            <b><span>{{a.posted_on}}</span></b>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endblock %}

    {% block pagination %}
    <!--pagination-->
     <section class="mb-5">
        <div class="container">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        {% if articles.has_previous %}
                        <a class="page-link" href="?page={{ articles.previous_page_number }}">Prev</a>
                        {% endif %}
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a>
                    </li>
                    <li class="page-item">
                        {% if articles.has_next %}
                        <a class="page-link" href="?page={{ articles.next_page_number }}">Next</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        </div>
    </section>
    {% endblock %}

blog/templates/category_list.html
{% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <!--category-->
    <section class="create-new-post mb-5">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'blog:create_new_category' %}"><button class="btn btn-outline-dark float-right mb-1">Create new category</button></a>
                    {% endif %}
                    <table class="table table-dark table-bordered">
                        <thead>
                            <tr class="text-center">
                                <th>Title</th>
                                {% if request.user.is_authenticated %}
                                {% if request.user.is_superuser or request.user.is_staff %}
                                <th>Action</th>
                                {% endif %}
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for cat in categories %}
                            <tr class="text-center">
                                <td>{{cat.name}}</td>
                                {% if request.user.is_authenticated %}
                                {% if request.user.is_superuser or request.user.is_staff %}
                                <td><a href="{% url 'blog:delete_category' id=cat.id %}">Delete</a> || <a href="{% url 'blog:update_category' id=cat.id %}">Update</a></td>
                                {% endif %}
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

    {% block pagination %}
    <!--pagination-->
     <section class="mb-5">
        <div class="container">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        {% if categories.has_previous %}
                        <a class="page-link" href="?page={{ categories.previous_page_number }}">Prev</a>
                        {% endif %}
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="">Page {{ categories.number }} of {{ categories.paginator.num_pages }}.</a>
                    </li>
                    <li class="page-item">
                        {% if categories.has_next %}
                        <a class="page-link" href="?page={{ categories.next_page_number }}">Next</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        </div>
    </section>
    {% endblock %}

blog/templates/create_author.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <section class="create-new-post">
        <div class="container">
            <div class="row">
                <div class="col">
                    <form method="POST" class="mt-4 mb-5" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-outline-info">Create Author</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

blog/templates/create_new_article.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <section class="create-new-post">
        <div class="container">
            <div class="row">
                <div class="col">
                    <form method="POST" class="mt-4 mb-5" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.media}}
                        {{form.as_p}}
                        <button class="btn btn-outline-info">Create Article</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

blog/templates/create_new_category.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <section class="create-new-post">
        <div class="container">
            <div class="row">
                <div class="col">
                    <form method="POST" class="mt-4 mb-5" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-outline-info">Create Article</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}

    {% block bgImage %}
    <!-- bg image -->

    <section class="bg-image">

    </section>
    {% endblock %}

    {% block scrolling %}
    <!-- scrolling -->
    <div class="tricker-wrapper">
        <div class="text-update">
            <p>Education leads of life, So share your knowledge without any arrogance</p>
        </div>
    </div>
    {% endblock %}

    {% block heading %}
    <!--heading-->
    <div class="heading">
        <p>Articles</p>
    </div>
    {% endblock %}


    {% block content %}
    <!--main content-->
    <section>
        <div class="container">
            <div class="row mb-4">
                {% for a in articles %}
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card mb-4" style="box-shadow:1px 1px 0px 0px gray">
                        <a href="{{a.single_page_url}}"><img src="{{a.image.url}}" class="card-img-top" alt="" srcset=""></a>
                        <div class="card-body">
                            <b><a href="{{a.category_page_url}}">{{a.category.name}}</a></b>
                            <a href="{{a.single_page_url}}"><strong>{{a.title|truncatewords:3}}.</strong></a>
                            <b><a href="{{a.article_author_url}}">{{a.article_author.name.get_full_name}}</a></b>
                        </div>
                        <div class="card-footer">
                            <b><span>{{a.posted_on}}</span></b>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endblock %}

    {% block pagination %}
    <!--pagination-->
     <section class="mb-5">
        <div class="container">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        {% if articles.has_previous %}
                        <a class="page-link" href="?page={{ articles.previous_page_number }}">Prev</a>
                        {% endif %}
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a>
                    </li>
                    <li class="page-item">
                        {% if articles.has_next %}
                        <a class="page-link" href="?page={{ articles.next_page_number }}">Next</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        </div>
    </section>
    {% endblock %}

blog/templates/logged_in_author.html
{% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <section class="create-new-post mb-5">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    <a href="{% url 'blog:create_new_article' %}"><button class="btn btn-outline-dark float-right mb-1">Create new article</button></a>
                    <table class="table table-dark table-bordered">
                        <thead>
                            <tr class="text-center">
                                <th>Title</th>
                                <th>Posted On</th>
                                {% if request.user.is_authenticated %}
                                {% if request.user.is_superuser or request.user.is_staff %}
                                <th>Action</th>
                                {% endif %}
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for a in articles %}
                            <tr class="text-center">
                                <td>{{a.title}}</td>
                                <td>{{a.posted_on}}</td>
                                {% if request.user.is_authenticated %}
                                {% if request.user.is_superuser or request.user.is_staff %}
                                <td><a href="{% url 'blog:delete_article' id=a.id %}">Delete</a> || <a href="{% url 'blog:article_update' id=a.id %}">Update</a></td>
                                {% endif %}
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

    {% block pagination %}
    <!--pagination-->
     <section class="mb-5">
        <div class="container">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        {% if articles.has_previous %}
                        <a class="page-link" href="?page={{ articles.previous_page_number }}">Prev</a>
                        {% endif %}
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="">Page {{ articles.number }} of {{ articles.paginator.num_pages }}.</a>
                    </li>
                    <li class="page-item">
                        {% if articles.has_next %}
                        <a class="page-link" href="?page={{ articles.next_page_number }}">Next</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
        </div>
    </section>
    {% endblock %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <!-- login -->
    <div class="container login-page">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card bg-primary text-center card-form" style="box-shadow:2px 0px 3px 0px gray">
                    <div class="card-body">
                        <h3>Sign In Today</h3>
                        <h6>Please fill out this form to login</h6>
                        {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            {{ message }}
                        </div>
                        {% endfor %}
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control form-control-lg" placeholder="Username" name="username">
                            </div>                                                                
                            <div class="form-group">
                                <input type="password" class="form-control form-control-lg" placeholder="Password" name="password">
                            </div>                                               
                            <button class="btn btn-outline-light btn-block">Submit</button>
                            <div class="mt-2">
                                <b style="color:white; float:left" class="mr-1">Are you new here?</b>
                                <a href="{% url 'blog:registration' %}" style="float:left">Register now</a>
                            </div>
                        </form>                              
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

blog/templates/pdf.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>Article Documentation</title>
    </head>
    <body>
        <img src="media/{{article.image}}" style="height:400px; display:block; margin-left:auto; margin-right:auto; width:10%" alt="">
        <h1 style="text-align:center">{{article.title}}</h1>
        <p style="text-align:center">{{article.text}}</p>
        <p style="text-align:center">{{article.category.name}}</p>
        <p style="text-align:center">{{article.posted_on}}</p>
    </body>
</html>

blog/templates/single.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <!--single page-->
    <section class="single-page">
        {% if article.id > first.id %}
        <a href="{% url 'blog:single_page' id=article.id|add:'-1' %}" class="prev p-3" style="text-decoration: none;">Prev</a>
        {% endif %}
        {% if article.id < last.id %}
        <a href="{% url 'blog:single_page' id=article.id|add:'1' %}" class="next p-3" style="text-decoration: none;">Next</a>
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card text-center mb-4">
                        <img src="{{article.image.url}}" class="card-img-top" alt="" srcset="" style="height:600px">
                        <div class="card-body">                    
                            <b><a href="{{article.category_page_url}}">{{article.category.name}}</a></b>
                            <strong class="text-muted">{{article.title}}</strong>
                            <b><a href="{{article.article_author_url}}">{{article.article_author.name.get_full_name}}</a></b>
                        </div>
                        <p>{{ article.text| safe}}.</p>
                        <div class="card-footer">
                            <b><span>{{article.posted_on}}</span></b>
                        </div>
                    </div>
                    <a href="{% url 'blog:pdf' id=article.id %}" class="btn btn-danger btn-lg" target="_blank">Download PDF</a>
                    <div class="heading">
                        <p>Related Articles {{article.category.name}}</p>
                    </div>
                    {% for r in related_articles %}
                    <div class="card text-center mb-5">
                        <img src="{{r.image.url}}" class="card-img-top" alt="" srcset="" style="height: 600px;">
                        <div class="card-body">                                                
                            <b><a href="{{r.category_page_url}}">{{r.category.name}}</a></b>
                            <strong class="text-muted">{{r.title}}.</strong>
                            <b><a href="{{r.article_author_url}}">{{r.article_author.name.get_full_name}}</a></b>
                        </div>
                        <p>{{ r.text|safe }}.</p>
                        <div class="card-footer">
                            <b><span>{{r.posted_on}}</span></b>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>    
    </section>
    {% endblock %}

    {% block show_comment %}
    <!--display comments-->
    <section class="comment-list mt-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3><strong>Comments</strong></h3>
                    <ol style="border:0px">
                        <div class="comment-content">
                            <div>
                                {% for comment in comments %}
                                <div style="background:#f0f0f0">
                                    <i class="fas fa-user"></i>
                                    <span class="comment-author">{{comment.name}}</span>
                                </div>
                                <p style="margin-left:17px; margin-top:7px">{{comment.text}}</p>
                                {% empty %}
                                <p>No comment found</p>
                                {% endfor %}
                            </div>
                        </div>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

    {% block comment %}
    <!-- comment -->
    <section class="mt-5 mb-5 comment">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <b>Comment</b>
                    <p class="mt-2">Thank you for reading. Leave a comment below and let us know what do you think of this article.</p>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-comment mt-3">Post comment</button>                    
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}